language: java
dist: trusty
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  # - oraclejdk-ea
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk-ea
before_install:
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
  - tar xzvf apache-maven-3.6.0-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.0/bin:$PATH
  - bash ./.configure-maven.sh
